" =========================================================
" ~/.config/vim/vimrc - FUNCIONAL 100%
" Todo centralizado en ~/.config/vim/
" =========================================================

" vim-plug (plug.vim está en ~/.vim/autoload/)
call plug#begin('~/.config/vim/plugged')

" Plugins equivalentes a Neovim
Plug 'preservim/nerdtree'
Plug 'tpope/vim-fugitive' 
Plug 'ctrlpvim/ctrlp.vim'

call plug#end()

" Configuración básica (igual Neovim)
set nocompatible
syntax enable
set termguicolors
set number
set relativenumber
set cursorline
set signcolumn=yes
set mouse=a
set splitright
set splitbelow
set scrolloff=8
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set clipboard=unnamedplus

" Líderes
let mapleader = " "
let maplocalleader = "\\"

" Cursor block normal / barra insert
set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50

" Tema (está en ~/.config/vim/colors/ vía symlink)
colorscheme theme

" =====================================================
" KEYMAPS (DESPUÉS de plug#end() - CRUCIAL)
" =====================================================
nnoremap <C-n> :NERDTreeToggle<CR>
nnoremap <leader>e :NERDTreeFocus<CR>

nnoremap <leader>w :w<CR>
nnoremap <C-s> :w<CR>
nnoremap <leader>q :q<CR>

nnoremap n nzzzv
nnoremap N Nzzzv

vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

nnoremap <leader>h <C-w>h
nnoremap <leader>j <C-w>j
nnoremap <leader>k <C-w>k
nnoremap <leader>l <C-w>l

nnoremap <leader>gs :Git<CR>
nnoremap <leader>gc :Git commit<CR>
nnoremap <leader>ff :CtrlP<CR>

nnoremap <leader>ve :edit $HOME/.config/vim/vimrc<CR>
nnoremap <leader>vr :source $HOME/.config/vim/vimrc<CR>

" Desactivar netrw
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1


" Silenciar warnings deprecated de NERDTree
let g:NERDTreeRespectWildIgnore = 1
let g:NERDTreeLimitedSyntax = 1
