# CONFIGURACIÓN STARSHIP: NETENEBRAE

add_newline = false

format = """
[┌─](bold gray3)$os$username$directory$git_branch$git_status
[└─](bold gray3)$character"""

right_format = """$cmd_duration$time"""

palette = "NeTenebrae"

[palettes.NeTenebrae]
red_root = "#ff4d4d"    # Rojo neón claro (mantenemos para root)
frost_user = "#89dceb"   # Gris metal gélido (desaturado y frío)
gray_icons = "#a9b1d6"  # Gris Platino
gray3 = "#6E6E6E" 

[os]
disabled = false
style = "bold gray_icons"
format = "[$symbol]($style) "

[os.symbols]
Arch = "󰣇"
Kali = ""
Ubuntu = "󰕈"
Debian = "󰣚"
Windows = "󰍲"
Linux = "󰌽"

[username]
show_always = true
# Usuario ahora en tono gélido y desaturado
style_user = "bold frost_user"
style_root = "bold red_root"
format = "[$user]($style) "

[directory]
style = "bold white"
read_only = " 󰌾"
truncation_length = 1
truncation_symbol = "󰇘/"
format = "in [󰉋 ](bold gray_icons)[$path]($style)[$read_only]($style) "

[git_branch]
symbol = "󰊢 "
style = "bold gray3"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold gray_icons"
format = '([\[$all_status$ahead_behind\]]($style)) '
stashed = "≡"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
conflicted = "="
deleted = "×"
modified = "!"
untracked = "?"

[character]
# Mantenemos el puntero en gris para minimalismo
success_symbol = "[>>](bold gray_icons) "
error_symbol = "[!!](bold red_root) "

[cmd_duration]
min_time = 2000
style = "italic gray3"
format = "[󱎫 ](gray_icons)[$duration]($style) "

[time]
disabled = false
time_format = "%H:%M"
style = "bold gray3"
format = "at [󱑎 ](gray_icons)[$time]($style)"

[line_break]
disabled = false
