conky.config = {
  update_interval = 1.5,
  double_buffer = true,
  no_buffers = true,
  text_buffer_size = 32768,

  own_window = true,
  own_window_class = 'Conky',
  own_window_type = 'desktop',
  own_window_transparent = false,
  own_window_colour = '#050505',
  own_window_argb_visual = true,
  own_window_argb_value = 210,
  own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
  border_inner_margin = 15,

  alignment = 'bottom_left',
  gap_x = 40,
  gap_y = 40,
  minimum_width = 400,

  use_xft = true,
  font = 'JetBrainsMono Nerd Font:size=9',
  uppercase = true,
  short_units = true,

  default_color = '#FFFFFF',
  color1 = '#FFFFFF',
  color2 = '#B0B0B0',
};

conky.text = [[
${color1}${font :style=Bold:size=18}NETWORK${font} ${alignr}${voffset 5}${color2}DNS :: ${color}${execi 60 awk 'NF && $1=="nameserver"{print $2; exit}' /etc/resolv.conf}
${voffset -5}${color1}${hr 1}${color}

${voffset 2}${color2}IFACE :: ${color}${gw_iface}${alignr}${color2}PING :: ${color}${execi 5 ping -c 1 8.8.8.8 | grep 'time=' | awk -F'time=' '{print $2}' | cut -d ' ' -f 1} ms
${color2}DOWN  :: ${color}${downspeed ${gw_iface}} ${alignr}${color2}UP :: ${color}${upspeed ${gw_iface}}
${voffset 2}${color1}${downspeedgraph ${gw_iface} 20,195} ${alignr}${upspeedgraph ${gw_iface} 20,195}

${voffset 5}${color1}${font :style=Bold:size=14}STORAGE${font}
${voffset -5}${color1}${hr 1}${color}
${color2}ROOT ${color}${fs_used_perc /}% ${alignr}${fs_used /} / ${fs_size /}
${color1}${fs_bar 8 /}
${if_mounted /home}${voffset 2}${color2}HOME ${color}${fs_used_perc /home}% ${alignr}${fs_used /home} / ${fs_size /home}
${color1}${fs_bar 8 /home}${voffset 2}${endif}

${voffset 5}${color1}${font :style=Bold:size=14}TOP PROCESSES${font}
${voffset -5}${color1}${hr 1}${color}
${voffset 2}${color2}${top name 1} ${alignr}${color}${top cpu 1}%
${voffset -2}${color2}${top name 2} ${alignr}${color}${top cpu 2}%
${voffset -2}${color2}${top name 3} ${alignr}${color}${top cpu 3}%
${voffset -2}${color2}${top name 4} ${alignr}${color}${top cpu 4}%
]];