conky.config = {
  update_interval = 1.5,
  double_buffer = true,
  no_buffers = true,
  text_buffer_size = 32768,

  own_window = true,
  own_window_class = 'Conky',
  own_window_type = 'desktop',
  own_window_transparent = false,
  own_window_colour = '#050505',
  own_window_argb_visual = true,
  own_window_argb_value = 210,
  own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
  border_inner_margin = 15,

  alignment = 'bottom_left',
  gap_x = 40,
  gap_y = 30,
  minimum_width = 400,

  use_xft = true,
  font = 'JetBrainsMono Nerd Font:size=9',
  uppercase = true,
  short_units = true,

  default_color = '#FFFFFF',
  color1 = '#FFFFFF',
  color2 = '#B0B0B0',
};

conky.text = [[
${color1}${font :style=Bold:size=28}NETWORK${font} ${alignr}${voffset -18}${font :style=Bold:size=10}DNS${font}
${alignr}${voffset -2}${font :size=9}${color2}${texeci 60 nmcli -t -f IP4.DNS dev show | head -n1 | awk -F: '{print $2}' | sed -e 's/9.9.9.9/QUAD9/g' -e 's/149.112.112.112/QUAD9/g' -e 's/8.8.8.8/GOOGLE/g' -e 's/1.1.1.1/CLOUDFLARE/g' | awk '{if ($1 ~ /^[0-9.]+$/ || $1 == "") print "ISP"; else print $1}'}${font}${color}
${voffset -10}${color1}${hr 1}${color}

${voffset 2}${color2}IFACE :: ${color}${if_up proton0}proton0${else}${gw_iface}${endif}${goto 310}${color2}PING :: ${color}${texeci 5 ping -c 1 -W 1 8.8.8.8 > /dev/null && ping -c 1 -W 1 8.8.8.8 | grep 'time=' | awk -F'time=' '{print $2}' | cut -d ' ' -f 1 | cut -d '.' -f 1 | sed 's/$/ ms/' || echo "OFFLINE"}
${voffset -3}${color2}UP    :: ${color}${if_up proton0}${upspeed proton0}${else}${upspeed ${gw_iface}}${endif}/s${goto 310}${color2}DOWN :: ${color}${if_up proton0}${downspeed proton0}${else}${downspeed ${gw_iface}}${endif}/s
${voffset 1}${color #FFFFFF}${if_up proton0}${upspeedgraph proton0 14,195 FFFFFF FFFFFF -m 10000}${else}${upspeedgraph ${gw_iface} 14,195 FFFFFF FFFFFF -m 10000}${endif} ${alignr}${color #FFFFFF}${if_up proton0}${downspeedgraph proton0 14,195 FFFFFF FFFFFF -m 50000}${else}${downspeedgraph ${gw_iface} 14,195 FFFFFF FFFFFF -m 50000}${endif}

${voffset 4}${color1}${font :style=Bold:size=18}STORAGE${font} ${alignr}${voffset -18}${font :style=Bold:size=10}${color2}FSTYPE${font}
${alignr}${voffset -2}${font :size=9}${color}${fs_type /}${font}
${voffset -10}${color1}${hr 1}${color}

${voffset 2}${color2}LVM-ROOT ${color}${fs_used_perc /}% ${alignr}${fs_used /} / ${fs_size /}
${voffset -4}${color1}${fs_bar 6 /}
${if_mounted /home}${voffset 2}${color2}LVM-HOME ${color}${fs_used_perc /home}% ${alignr}${fs_used /home} / ${fs_size /home}
${voffset -4}${color1}${fs_bar 6 /home}${endif}

${voffset 4}${color1}${font :style=Bold:size=18}PROCESSES${font}${voffset -2}${goto 325}${font :style=Bold:size=9}${color2}CPU${goto 365}RAM${font}
${voffset -10}${color1}${hr 1}${color}

${voffset 2}${color2}${top name 1} ${goto 310}${color}${top cpu 1}%${goto 365}${top mem_res 1}
${voffset -4}${color2}${top name 2} ${goto 310}${color}${top cpu 2}%${goto 365}${top mem_res 2}
${voffset -4}${color2}${top name 3} ${goto 310}${color}${top cpu 3}%${goto 365}${top mem_res 3}
${voffset -4}${color2}${top name 4} ${goto 310}${color}${top cpu 4}%${goto 365}${top mem_res 4}
]];