conky.config = {
  update_interval = 1.5,
  double_buffer = true,
  no_buffers = true,
  text_buffer_size = 32768,

  own_window = true,
  own_window_class = 'Conky',
  own_window_type = 'desktop',
  own_window_transparent = false,
  own_window_colour = '#050505',
  own_window_argb_visual = true,
  own_window_argb_value = 210,
  own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
  border_inner_margin = 15,

  alignment = 'top_left',
  gap_x = 40,
  gap_y = 50,
  minimum_width = 400,

  use_xft = true,
  font = 'JetBrainsMono Nerd Font:size=9',
  uppercase = true,
  short_units = true,

  default_color = '#FFFFFF',
  color1 = '#FFFFFF',
  color2 = '#B0B0B0',
};

conky.text = [[
${color1}${font JetBrainsMono Nerd Font:style=Bold:size=38}${time %I:%M}${font}${voffset -10}${font :style=Bold:size=16} ${time %p}${font} ${alignr}${voffset -36}${font :style=Bold:size=11}${time %A}${font}
${alignr}${voffset -2}${font :size=10}${time %d %b %Y}${font}${color}
${voffset 14}${color1}${hr 1}${color}

${voffset 10}${color2}${execi 600 lscpu | grep "Model name" | cut -d: -f2 | sed -e 's/^[ \t]*//' -e 's/(R)//g' -e 's/(TM)//g' -e 's/CPU//g' | awk '{print $1,$2,$3}'} ${color}${cpu cpu0}% @ ${freq_g}GHz ${alignr}${color2}TEMP ::  ${color}${hwmon 1 temp 1}°C
${voffset -2}${color1}${cpubar 8}

${voffset 6}${color2}RAM ${color}${memperc}% (${mem}/${memmax}) ${alignr}${color2}USED :: ${color}${mem}
${voffset -2}${color1}${membar 8}

${voffset 10}${color2}UPTIME :: ${color}${uptime_short} ${alignr}${color2}OS :: ${color}${execi 600 grep ^ID= /etc/os-release | cut -d= -f2 | tr -d '"'}
${voffset -2}${color2}KERNEL :: ${color}${exec uname -r | cut -d- -f1} (${exec uname -r | awk -F- '{print $2}' | sed 's/[0-9]*//g'}) ${alignr}${color2}PACKS :: ${color}${execi 3600 pacman -Q | wc -l}
]];