local home = os.getenv("HOME")

conky.config = {
    lua_load = home .. '/.config/conky/lua/system.lua',
    lua_draw_hook_pre = 'conky_system_main',
    
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    
    alignment = 'top_left',
    gap_x = 10, gap_y = 30,
    minimum_width = 245, minimum_height = 410, -- Aumentado
    update_interval = 1.0,
    double_buffer = true,
};

conky.text = [[ ]];