name: Update neBSPWM News
on:
  schedule:
    - cron: '0 0 * * *' # Cada 24 horas (00:00 UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-nebspwm:
    name: Update README with project news
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "NEBSPWM"
          feed_list: "https://rss.app/feeds/YrQvqeV8oDOWBw8C.xml"
          max_post_count: 5
          
          # LIMPIEZA NATIVA: Esto elimina imágenes y etiquetas HTML automáticamente
          clean_html: true
          
          # FILTRO SEGURO: Solo pasa si contiene bspwm (insensible a mayúsculas)
          item_exec: "post.description.toLowerCase().includes('bspwm') ? post : null"

          # TEMPLATE: Usamos $description que ahora vendrá limpia por 'clean_html'
          template: "<tr><td>$date</td><td><a href='$url'>$description</a></td></tr>"
          date_format: "dd/mm/yyyy"
          
          commit_message: "Bot: Update diario neBSPWM"
          committer_username: "blog-post-bot"
          committer_email: "blog-post-bot@example.com"
