name: Latest Blog Post Workflow
on:
  schedule:
    # Se ejecuta cada hora
    - cron: '0 * * * *'
  workflow_dispatch:

# Permisos necesarios para escribir en el README
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull rss feed
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: NEBSPWM
          feed_list: "https://rss.app/feeds/YrQvqeV8oDOWBw8C.xml"
          max_post_count: 3
          # Código JS para filtrar por la palabra neBSPWM
          item_exec: |
            (function() {
              var desc = post.description || "";
              var title = post.title || "";
              var keyword = /neBSPWM/i;
              if (desc.match(keyword) || title.match(keyword)) {
                return post;
              } else {
                return null;
              }
            })()
          # Template mejorado con saltos de línea y negritas
          template: |
            - **$date** | [$title]($url)
            
          date_format: dd/mm/yyyy
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          readme_path: "./README.md"
          commit_message: "Updated with the latest blog posts"
          committer_username: "blog-post-bot"
          committer_email: "blog-post-bot@example.com"
